chore(): upgrade dotfile bin

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,14 +1,5 @@
 #!/bin/bash
 
-#color codes
-RED='\033[1;31m'
-YELLOW='\033[1;33m'
-BLUE="\\033[38;5;27m"
-SEA="\\033[38;5;49m"
-GREEN='\033[1;32m'
-CYAN='\033[1;36m'
-NC='\033[0m'
-
 #emoji codes
 CHECK_MARK="${GREEN}\xE2\x9C\x94${NC}"
 X_MARK="${RED}\xE2\x9C\x96${NC}"
@@ -20,6 +11,69 @@ HOT="${ORANGE}\xF0\x9F\x94\xA5${NC}"
 WARNING="${RED}\xF0\x9F\x9A\xA8${NC}"
 RIGHT_ANGLE="${GREEN}\xE2\x88\x9F${NC}"
 
+# color codes
+RESTORE='\033[0m'
+NC='\033[0m'
+BLACK='\033[00;30m'
+RED='\033[00;31m'
+GREEN='\033[00;32m'
+YELLOW='\033[00;33m'
+BLUE='\033[00;34m'
+PURPLE='\033[00;35m'
+CYAN='\033[00;36m'
+SEA="\\033[38;5;49m"
+LIGHTGRAY='\033[00;37m'
+LBLACK='\033[01;30m'
+LRED='\033[01;31m'
+LGREEN='\033[01;32m'
+LYELLOW='\033[01;33m'
+LBLUE='\033[01;34m'
+LPURPLE='\033[01;35m'
+LCYAN='\033[01;36m'
+WHITE='\033[01;37m'
+OVERWRITE='\e[1A\e[K'
+
+DOTFILES_LOG="$HOME/.dotfiles.log"
+
+
+# _header colorize the given argument with spacing
+function _task {
+    # if _task is called while a task was set, complete the previous
+    if [[ $TASK != "" ]]; then
+        printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
+    fi
+    # set new task title and print
+    TASK=$1
+    printf "${LBLACK} [ ]  ${TASK} \n${LRED}"
+}
+
+# _cmd performs commands with error checking
+function _cmd {
+    #create log if it doesn't exist
+    if ! [[ -f $DOTFILES_LOG ]]; then
+        touch $DOTFILES_LOG
+    fi
+    # empty conduro.log
+    > $DOTFILES_LOG
+    # hide stdout, on error we print and exit
+    if eval "$1" 1> /dev/null 2> $DOTFILES_LOG; then
+        return 0 # success
+    fi
+    # read error from log and add spacing
+    printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
+    while read line; do
+        printf "      ${line}\n"
+    done < $DOTFILES_LOG
+    printf "\n"
+    # remove log file
+    rm $DOTFILES_LOG
+    # exit installation
+    exit 1
+}
+
+
+set -e
+
 # Paths
 CONFIG_DIR="$HOME/.config/dotfiles"
 VAULT_SECRET="$HOME/.ansible-vault/vault.secret"
@@ -28,44 +82,38 @@ SSH_DIR="$HOME/.ssh"
 IS_FIRST_RUN="$HOME/.dotfiles_run"
 
 # Install Homebrew
-  echo -e "${ARROW} ${CYAN}Homebrew...${NC}"
-if [[ $(brew --version) ]] ; then
-    echo -e "   ${RIGHT_ANGLE} ${CYAN}Homebrew is installed${NC}"
-else
-    echo -e "   ${RIGHT_ANGLE} ${CYAN}Attempting to install Homebrew${NC}"
-    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+if ! [[ $(brew --version) ]] ; then
+    _task "Homebrew..."
+        _cmd "/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
 fi
 
 # Install Ansible
-echo -e "${ARROW} ${CYAN}Ansible...${NC}"
 if ! command -v ansible > /dev/null 2>&1; then
-    echo -e "   ${RIGHT_ANGLE} ${CYAN}Attempting to install Ansible${NC}"
-    brew install ansible 2>&1 > /dev/null
+    _task "Installing Ansible..."
+        _cmd "brew install ansible"
 fi
 
 # Clone repository
 if ! [[ -d "$DOTFILES_DIR" ]]; then
-    echo -e "${ARROW} ${CYAN}Cloning repository: ${YELLOW}github.com/codepainter/dotfiles-v2${NC}"
-    git clone --quiet "https://github.com/codepainter/dotfiles-v2.git" "$DOTFILES_DIR" 2>&1 > /dev/null
+    _task "Clone Repository..."
+        _cmd "git clone --quiet "https://github.com/codepainter/dotfiles-v2.git" $DOTFILES_DIR"
 else
-    echo -e "${ARROW} ${CYAN}Updating repository: ${YELLOW}github.com/codepainter/dotfiles-v2${NC}"
-    git -C "$DOTFILES_DIR" pull --quiet > /dev/null
+    _task "Update Repository..."
+        _cmd "git -C "$DOTFILES_DIR" pull --quiet"
 fi
 
 # Create path
 pushd "$DOTFILES_DIR" 2>&1 > /dev/null
 
 # Update Galaxy
-echo -e "${ARROW} ${CYAN}Updating Galaxy...${NC}"
-ansible-galaxy install -r requirements.yml 2>&1 > /dev/null
+_task "Update Ansible Galaxy..."
+    _cmd "ansible-galaxy install -r requirements.yml"
 
 # Run playbook
-echo -e "${ARROW} ${CYAN}Running playbook...${NC}"
+_task "Running Ansible Playbook..."
 if [[ -f $VAULT_SECRET ]]; then
-    echo -e "${ARROW} ${CYAN}Using vault config file...${NC}"
     ansible-playbook --vault-password-file $VAULT_SECRET "$DOTFILES_DIR/main.yml" "$@"
 else
-    echo -e "${WARNING} ${CYAN}Vault config file not found...${NC}"
     ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
 fi
 
